---
title: "Survival Analysis"
author: "Roxy Zhang"
date: "4/19/2022"
output: github_document
---

```{r setup, include=FALSE}
library(survival)
library(MASS)
library(KMsurv)
```

## Question 2

```{r}
time = c(1, 2, 2, 4, 5, 6, 7, 8, 9, 10)

event = c(1, 1, 1, 0, 0, 1, 0, 0, 0, 0)

surv_obj = Surv(time, event == 1)

km_fit = survfit(surv_obj ~ 1, type = "kaplan-meier")

summary(km_fit)

plot(km_fit)
```

```{r}
# Kaplan-Meier, Nelson-Aalen, Fleming-Harrington estimate
cbind(km_fit$time, 
      km_fit$surv, 
      cumsum(km_fit$n.event/km_fit$n.risk), 
      exp(-cumsum(km_fit$n.event/km_fit$n.risk)))
```



## Question 3

```{r}
data("tongue")

aneuploid = subset(tongue, type == 1)
diploid = subset(tongue, type == 2)

aneuploid$surv_obj <- with(aneuploid, Surv(time, delta == 1))
diploid$surv_obj <- with(diploid , Surv(time, delta == 1))

km_aneuploid <- survfit(surv_obj ~ type, 
                        conf.type="log",
                        type = "kaplan-meier", 
                        data = aneuploid)

summary(km_aneuploid)

plot(km_aneuploid,
     mark.time = T,
     main="Kaplan-Meier Estimate of Aneuploid",
     ylab = "Survival Probability", 
     xlab = "Time to Death in Week")


km_diploid = survfit(surv_obj~type, 
                     conf.type="log",
                     type = "kaplan-meier",
                     data=diploid)

summary(km_diploid)

plot(km_diploid, 
     mark.time = T,
     main="Kaplan-Meier Estimates of Diploid",
     ylab = "Survival Probability",
     xlab="Time to Death in Weeks")
```

```{r}
# survival rate at 1 yr (52 weeks), with CI
summary(km_aneuploid,time = c(52))

summary(km_diploid,time = c(52))
```

